# Generated by Django 4.1.7 on 2023-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
